#!/usr/bin/env bash
set -euo pipefail

# cut-release.sh <version> — prepare a release PR.
#
#   1. bump VERSION + sync derived files (package.json, plugin.json)
#   2. regenerate CHANGELOG.md from Conventional Commits (git-cliff)
#   3. open a "release: <version>" PR — and STOP.
#
# Merging the PR and pushing the tag are deliberately left to a human: review the
# version bump + changelog, merge, then push the tag. This script NEVER enables
# auto-merge and NEVER publishes — the two outward, irreversible steps (the merge
# and the tag push that publishes) each stay behind an explicit human gate.
#
# The tag push fires .github/workflows/release.yml (npm publish + GitHub
# Release, whose notes are generated by git-cliff). `main` is a protected branch
# with required status checks, so the release commit must land via a PR — a
# direct push is rejected. Tags aren't protected, so the tag push is direct.
#
# Requires: git-cliff (brew install git-cliff | cargo install git-cliff |
#           https://github.com/orhun/git-cliff/releases) and gh authenticated
#           as the fujibee account (direnv pins GH_TOKEN for this repo).
#
# Usage: scripts/release/cut-release.sh 1.0.4

die() { echo "cut-release: $*" >&2; exit 1; }

VERSION="${1:-}"
[ -n "$VERSION" ] || die "usage: cut-release.sh <version>  (semver, no leading 'v')"
case "$VERSION" in
  v*) die "version must not start with 'v' (got '$VERSION')" ;;
  [0-9]*.[0-9]*.[0-9]*) ;;
  *) die "version must be semver MAJOR.MINOR.PATCH (got '$VERSION')" ;;
esac

ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
cd "$ROOT"

command -v git-cliff >/dev/null 2>&1 \
  || die "git-cliff not found — install it (brew install git-cliff) and retry"
command -v gh >/dev/null 2>&1 || die "gh not found"

# Must be on a clean, up-to-date main, and authenticated as fujibee.
[ -z "$(git status --porcelain)" ] || die "working tree is not clean"
[ "$(git rev-parse --abbrev-ref HEAD)" = "main" ] || die "must be on main"
git fetch origin -q
[ "$(git rev-parse HEAD)" = "$(git rev-parse origin/main)" ] \
  || die "local main is not in sync with origin/main — pull first"
who="$(gh api user --jq .login 2>/dev/null || true)"
[ "$who" = "fujibee" ] || die "gh identity is '$who', expected 'fujibee' (check direnv .envrc)"

TAG="v$VERSION"
git rev-parse "$TAG" >/dev/null 2>&1 && die "tag $TAG already exists"
BRANCH="release/$TAG"

echo "==> Preparing $TAG on branch $BRANCH"
git switch -c "$BRANCH"

# 1. bump + sync
echo "$VERSION" > VERSION
./scripts/release/sync-version.sh

# 2. regenerate the changelog including this release's section
git-cliff --tag "$TAG" -o CHANGELOG.md

# 3. commit + push the release PR
git add VERSION package.json .claude-plugin/plugin.json CHANGELOG.md
git commit -m "release: $VERSION"
git push -u origin "$BRANCH"

echo "==> Opening release PR"
gh pr create --base main --head "$BRANCH" \
  --title "release: $VERSION" \
  --body "Automated release of \`$VERSION\`.

- VERSION bump + synced \`package.json\` / \`.claude-plugin/plugin.json\`
- CHANGELOG.md regenerated from Conventional Commits

Merging this and pushing \`$TAG\` triggers the publish pipeline (npm + GitHub Release)."

# Intentionally STOP here. Auto-merge is never enabled; merging and tagging are
# human-gated (see the header). Print the remaining manual steps.
cat <<EOF

==> Release PR opened for $TAG. Auto-merge is intentionally NOT enabled.
    Finish the release by hand — each step is a deliberate gate:
      1. Review the PR: VERSION bump + the CHANGELOG [$VERSION] section.
      2. Wait for required checks, then merge:
           gh pr merge $BRANCH --squash --delete-branch
      3. Update main and tag (the tag push fires release.yml → npm publish):
           git switch main && git pull --ff-only origin main
           git tag $TAG && git push origin $TAG
      4. Approve the 'production' deployment when prompted, to publish to npm.
EOF
